# AlmaPay interactive and non-interactive operator configuration.
# shellcheck shell=bash

almapay_configure_paths() {
  printf '%s\n' "${ALMAPAY_DATA_ROOT}/almapay.env" "${ALMAPAY_DATA_ROOT}/secrets.env"
}

almapay_configure_domain_valid() {
  local domain="$1"
  [[ "${domain}" =~ ^[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]
}

almapay_read_tty() {
  local prompt="$1"
  local value=""
  if [[ ! -r /dev/tty ]]; then
    almapay_die "interactive input requires a terminal (/dev/tty)"
  fi
  printf '%s' "${prompt}" >/dev/tty
  IFS= read -r value </dev/tty
  almapay_trim "${value}"
}

almapay_read_secret_tty() {
  local prompt="$1"
  local value=""
  if [[ ! -r /dev/tty ]]; then
    almapay_die "interactive secret input requires a terminal (/dev/tty)"
  fi
  almapay_secrets_guard
  printf '%s' "${prompt}" >/dev/tty
  IFS= read -rs value </dev/tty
  printf '\n' >/dev/tty
  printf '%s' "${value}"
}

almapay_confirm_tty() {
  local prompt="$1"
  local default_no="${2:-1}"
  local answer
  answer="$(almapay_read_tty "${prompt}")"
  case "${answer}" in
    y|Y|yes|YES) return 0 ;;
    n|N|no|NO|'') [[ "${default_no}" -eq 0 ]] && return 0 || return 1 ;;
    *) return 1 ;;
  esac
}

almapay_generate_postgres_password() {
  local candidate=""
  while ((${#candidate} < 24)); do
    candidate="$(openssl rand -hex 24)"
  done
  printf '%s' "${candidate}"
}

almapay_postgres_password_valid() {
  local password="$1"
  ((${#password} >= 24)) &&
    [[ "${password}" =~ ^[A-Za-z0-9._~!%\^\&*+=:@-]+$ ]]
}

almapay_read_postgres_password_interactive() {
  local first="" second=""
  while true; do
    first="$(almapay_read_secret_tty "PostgreSQL password (Enter to auto-generate, or type one): ")"
    if [[ -z "${first}" ]]; then
      almapay_generate_postgres_password
      return 0
    fi
    if ! almapay_postgres_password_valid "${first}"; then
      almapay_error "password must be at least 24 characters and use safe characters"
      continue
    fi
    second="$(almapay_read_secret_tty "Confirm PostgreSQL password: ")"
    if [[ "${first}" == "${second}" ]]; then
      printf '%s' "${first}"
      return 0
    fi
    almapay_error "passwords did not match; try again"
  done
}

almapay_read_postgres_password_file() {
  local file="$1"
  local password=""
  [[ -f "${file}" ]] || almapay_die "postgres password file not found: ${file}"
  [[ ! -L "${file}" ]] || almapay_die "postgres password file must not be a symlink: ${file}"
  [[ "$(stat -c '%a' "${file}")" == "600" ]] ||
    almapay_die "postgres password file must have mode 0600: ${file}"
  almapay_secrets_guard
  IFS= read -r password <"${file}"
  almapay_postgres_password_valid "${password}" ||
    almapay_die "postgres password file does not contain a valid password"
  printf '%s' "${password}"
}

almapay_configure_write_files() {
  local domain="$1"
  local monero_mode="$2"
  local postgres_password="$3"
  local config_path="${ALMAPAY_DATA_ROOT}/almapay.env"
  local secrets_path="${ALMAPAY_DATA_ROOT}/secrets.env"

  install -d -o "${ALMAPAY_USER}" -g "${ALMAPAY_USER}" -m 0750 "${ALMAPAY_DATA_ROOT}"
  install -d -o "${ALMAPAY_USER}" -g "${ALMAPAY_USER}" -m 0700 "${ALMAPAY_DATA_ROOT}/secrets"

  umask 077
  cat >"${config_path}" <<EOF
# Generated by almapay configure
ALMAPAY_DOMAIN=${domain}
ALMAPAY_NETWORK=mainnet
ALMAPAY_LISTEN=${ALMAPAY_LISTEN_FIXED}
ALMAPAY_BITCOIN_MODE=local-pruned
ALMAPAY_MONERO_MODE=${monero_mode}
ALMAPAY_LIGHTNING_MODE=disabled
ALMAPAY_CARD_MODE=disabled
ALMAPAY_ACME_MODE=http-01
ALMAPAY_BACKUP_TARGET=
ALMAPAY_BACKUP_RETENTION_DAYS=30
ALMAPAY_INCLUDE_CHAIN_DATA_IN_BACKUP=false
EOF
  chmod 0640 "${config_path}"
  chown "${ALMAPAY_USER}:${ALMAPAY_USER}" "${config_path}"

  cat >"${secrets_path}" <<EOF
# Generated by almapay configure
POSTGRES_USER=postgres
POSTGRES_DB=postgres
POSTGRES_PASSWORD=${postgres_password}
EOF
  chmod 0600 "${secrets_path}"
  chown "${ALMAPAY_USER}:${ALMAPAY_USER}" "${secrets_path}"
  umask 022

  almapay_info "wrote ${config_path}"
  almapay_info "wrote ${secrets_path} (PostgreSQL password not displayed)"
}

almapay_install_caddy_config() {
  local rendered dest
  if [[ "$(id -u)" -ne 0 ]]; then
    almapay_die "install-caddy requires root"
  fi
  rendered="$(almapay_caddy_rendered_path)"
  dest="/etc/caddy/Caddyfile"
  [[ -f "${rendered}" ]] ||
    almapay_die "rendered Caddy source missing: ${rendered}; run install or render-caddy first"
  install -d -m 0755 /etc/caddy
  install -m 0644 "${rendered}" "${dest}"
  systemctl enable --now caddy >/dev/null 2>&1 || true
  systemctl reload caddy ||
    systemctl restart caddy ||
    almapay_die "caddy reload/restart failed"
  almapay_info "installed active Caddy configuration: ${dest}"
}

almapay_configure() {
  local domain=""
  local monero_mode="local-pruned"
  local force=0
  local noninteractive=0
  local install_caddy=0
  local set_postgres_password=0
  local postgres_password_file=""
  local postgres_password=""
  local config_path secrets_path
  local arg

  while ((${#@} > 0)); do
    case "$1" in
      --domain)
        shift
        domain="${1:-}"
        [[ -n "${domain}" ]] || almapay_die "--domain requires a value"
        shift
        ;;
      --no-monero)
        monero_mode="disabled"
        shift
        ;;
      --force)
        force=1
        shift
        ;;
      --noninteractive)
        noninteractive=1
        shift
        ;;
      --install-caddy)
        install_caddy=1
        shift
        ;;
      --set-postgres-password)
        set_postgres_password=1
        shift
        ;;
      --postgres-password-file)
        shift
        postgres_password_file="${1:-}"
        [[ -n "${postgres_password_file}" ]] ||
          almapay_die "--postgres-password-file requires a path"
        shift
        ;;
      *)
        almapay_die "unknown configure argument: $1"
        ;;
    esac
  done

  if [[ "${install_caddy}" -eq 1 && "${domain}${force}${noninteractive}${set_postgres_password}${postgres_password_file}" == "" && "$(id -u)" -eq 0 ]]; then
    almapay_install_caddy_config
    return 0
  fi

  id "${ALMAPAY_USER}" >/dev/null 2>&1 ||
    almapay_die "configure requires the ${ALMAPAY_USER} account; run bootstrap-host first"

  config_path="${ALMAPAY_DATA_ROOT}/almapay.env"
  secrets_path="${ALMAPAY_DATA_ROOT}/secrets.env"
  if [[ -f "${config_path}" || -f "${secrets_path}" ]]; then
    if [[ "${force}" -ne 1 ]]; then
      if [[ "${noninteractive}" -eq 1 ]]; then
        almapay_die "configuration files already exist; use --force to replace them"
      fi
      almapay_confirm_tty "Configuration files already exist. Overwrite? [y/N] " 1 ||
        almapay_die "configure cancelled"
    fi
  fi

  if [[ -z "${domain}" ]]; then
    if [[ "${noninteractive}" -eq 1 ]]; then
      almapay_die "noninteractive configure requires --domain"
    fi
    while true; do
      domain="$(almapay_read_tty "Public BTCPay domain: ")"
      if almapay_configure_domain_valid "${domain}"; then
        break
      fi
      almapay_error "enter a valid hostname (example: pay.example.com)"
    done
  fi
  almapay_configure_domain_valid "${domain}" ||
    almapay_die "invalid domain: ${domain}"

  if [[ -n "${postgres_password_file}" ]]; then
    postgres_password="$(almapay_read_postgres_password_file "${postgres_password_file}")"
  elif [[ -n "${ALMAPAY_CONFIGURE_POSTGRES_PASSWORD:-}" ]]; then
    almapay_secrets_guard
    postgres_password="${ALMAPAY_CONFIGURE_POSTGRES_PASSWORD}"
    almapay_postgres_password_valid "${postgres_password}" ||
      almapay_die "ALMAPAY_CONFIGURE_POSTGRES_PASSWORD is not valid"
  elif [[ "${set_postgres_password}" -eq 1 ]]; then
    if [[ "${noninteractive}" -eq 1 ]]; then
      almapay_die "noninteractive --set-postgres-password requires --postgres-password-file or ALMAPAY_CONFIGURE_POSTGRES_PASSWORD"
    fi
    postgres_password="$(almapay_read_postgres_password_interactive)"
  else
    postgres_password="$(almapay_generate_postgres_password)"
  fi

  if [[ "$(id -u)" -ne 0 ]]; then
    almapay_die "configure must run as root to install protected files owned by ${ALMAPAY_USER}"
  fi

  almapay_configure_write_files "${domain}" "${monero_mode}" "${postgres_password}"
  unset postgres_password

  almapay_info "configure complete: Monero=${monero_mode}; ACME email omitted"
  if [[ "${install_caddy}" -eq 1 ]]; then
    almapay_die "install-caddy requires rendered Caddy source; run install first, then: almapay configure --install-caddy"
  fi
}
